### PR TITLE
Add option for CODE_SIGN_STYLE

### PR DESCRIPTION
**Pull request by aeons**
This plugin does exactly what I want, except for setting `CODE_SIGN_STYLE` as well.

This PR adds that functionality, with an optional parameter, defaulting to doing nothing if it's not set.

### CODE REVIEW

**Review by p4checo — APPROVED** [review]
Sorry for the late review. 😇 And thanks for contributing!
Looks good! 👍

**Comment by p4checo** [comment]
Well, I just remembered that we had been invited to integrate cosigner's functionality into fastlane  a long time ago (#8), but we never actually did it 😅.

So, to close this chapter (and issue 😆) I just forked fastlane and created a branch (https://github.com/Mindera/fastlane/tree/integrate-mindera-cosigner-plugin) containing the main cosigner functionalities back into fastlane's existing `automatic_code_signing` action. I took the liberty of also migrating your recent changes (adding `CODE_SIGN_STYLE`). Hope you don't mind, and please say something if you do. 😉 

Needless to say I intend to open a PR on fastlane, but I would like for you and @portellaa to give me green light first.

Cheers! 🍻 

PS: Even though we are integrating cosigner into fastlane, I think we should still merge this PR and bump the version, so that current cosigner users can also benefit from this change 😄

**Comment by aeons** [comment]
Cool. Fine by me.

**Review by portellaa — APPROVED** [review]
Thanks a lot for your contribution @aeons 

I only have one doubt, so bear with me 😊 
Wouldn't this break all the purpose of this action? When we set the property, this will override the configs with whatever xcode decides, right?

What is the main usage of the action with this property? Can you provide an example?

I'm certainly mistaken, i just want to understand how will this behave 😉 

🍻

**Comment by aeons** [comment]
We want to have xcode manage signing in development, and then force it to manual in CI to sign with our enterprise cert.

**Comment by p4checo** [comment]
Excellent point, @portellaa

Apparently, `CODE_SIGN_STYLE` is the new name for `PROVISIONING_STYLE` key (which was introduced in Xcode 8, I think)

Guess Apple changed it to a more descriptive name in Xcode 9 😅  

Well, I guess that we should use a single parameter for this, and set the appropriate value according to the Xcode version, right?

My suggestion is that the existing `PROVISIONING_STYLE` is renamed to `CODE_SIGN_STYLE`, and we add logic to the plugin to look at Xcode version and update accordingly. A more brute force approach is to always set both keys, but it's a 🔨😆 .

Do you agree?

EDIT: It appears it's not possible to know for sure the Xcode's version, and we can's assume a given version from looking at the xcodeproj. Even if we were able to know, it would be possible for the project to have been upgraded to a new Xcode version (e.g. to test a beta), but the CI is still using the old version, causing issues. In conclusion, I think the best approach is perhaps to set both keys (`ProvisioningStyle` and `CODE_SIGN_STYLE`) on the xcodeproj.

**Comment by portellaa** [comment]
@p4checo i was thinking on `LastSwiftMigration` but we can't use it right? because it doesn't means that we have migrated the project to that Swift version. baaaaahhhh 😩

**Comment by aeons** [comment]
I don't have a strong opinion on this, so I'll defer to you guys.

**Comment by p4checo** [comment]
@portellaa I looked at that too, but we can't use it precisely for that reason.

@aeons No worries. I'll probably open a new PR with these changes (and close this one) and you can then take a look if you want, and even test on your workflow to see it it's working 😉

**Comment by p4checo** [comment]
Closing this one, because we will add this over at #11 

Thanks guys 😉👍

**Pull request closed without merging**
